name: Build Ladybird Browser

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: LadybirdBrowser/ladybird
      
      - name: Set up dependencies
        run: |
          rm -r CMakePresets.json
          wget https://raw.githubusercontent.com/techguy16/LadybirdBuild/refs/heads/main/CMakePresets2.json -O CMakePresets.json
          
          sudo apt update
          sudo apt install -y autoconf autoconf-archive automake build-essential ccache cmake curl fonts-liberation2 git libgl1-mesa-dev nasm ninja-build pkg-config qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip
          
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/kitware.list
          sudo apt update -y && sudo apt install cmake -y
          
          sudo wget -O /usr/share/keyrings/llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
          echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot.gpg.key] https://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-17 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list
          sudo apt update -y && sudo apt install clang-17 -y
          
          sudo apt install libpulse-dev -y
      
      - name: Build Ladybird
        run: |
          ./Meta/ladybird.sh build ladybird
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ladybird-build
          path: Build/release/
